apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
      initContainers:
        - name: db-migrations
          image: {{ .Values.image.repository }}:release-v.{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "manage_migrations.py", "upgrade"]
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
              ephemeral-storage: {{ .Values.resources.limits.ephemeral }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
              ephemeral-storage: {{ .Values.resources.requests.ephemeral }}
      containers:
        - name: main-app
          image: {{ .Values.image.repository }}:release-v.{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
              ephemeral-storage: {{ .Values.resources.limits.ephemeral }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
              ephemeral-storage: {{ .Values.resources.requests.ephemeral }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3


