apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
{{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
{{- end }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secret_key | quote }}
  ALGORITHM: {{ .Values.secrets.algorithm | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.secrets.access_token_expire_minutes | quote }}
  COINMARKETCAP_HOST: {{ .Values.secrets.coinmarketcap_host | quote }}

  MYSQL_HOST: {{ .Values.secrets.mysql_host | quote }}
  MYSQL_PORT: {{ .Values.secrets.mysql_port | quote }}
  MYSQL_USER: {{ .Values.secrets.mysql_user | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysql_pass | quote }}
  MYSQL_DATABASE: {{ .Values.secrets.mysql_name | quote }}
